### ISSUE TITLE
Element list loading

### ISSUE THREAD

**Issue by jbeaupuy** [actimeo/simmage-ui#101]
- [x] Add a loading icon while the data are retrieved
- [x] Display the number of results when loading is finished

**Comment by jbeaupuy** [comment]
- [ ] Improve design

**Comment by actimeo** [comment]
Warning, in documens.component.html you use several times (documents | async), which start an HTTP call each time. 
In this case you'll have to subscribe (and unsubscribe) to documents from the code instead of from the template
