### ISSUE TITLE
Admin: Users edition

### ISSUE THREAD

**Issue by actimeo** [actimeo/simmage-ui#16]
Users list
- [x] add an md-card-actions to each user and add an Edit button
- [x] add a button "Add a user" on toolbar
- [x] add a filter section (between toolbar and user list) with a filter "Usergroup" used to display the users of a specific usergroup only (add an entry 'admin only' to display users with NO usergroup)
- [x] when adding a new user from the list with a usergroup selected, pre-select this usergroup for new user

User edition
- [x] usergroup (or none for user admin)
- [x] participant: **create a generic 'select participant' component** 
- [x] admin rights
- [x] add a button to show the temporary password if there's one (create a new pg function to retrieve it from the database)
- [x] add a pg function to update an user (usergroup/rights/participant)

**Comment by jbeaupuy** [comment]
Other changes about this issue are in 42cda84

**Comment by jbeaupuy** [comment]
- [x] Improve design using ag-grid
